from dsu.runtime.constants.exceptions.custom_exception import CustomException


class AuthenticationError(CustomException):
    pass
