import pytest
from django_swagger_utils.drf_server.exceptions import NotFound, \
    ExpectationFailed
from mock import create_autospec

from ib_notifications.constants.exception_messages import INVALID_GROUP_ID, \
    EMPTY_USER_LIST
from ib_notifications.interactors.presenters.presenter_interface import \
    PresenterInterface
from ib_notifications.interactors.remove_users_from_group_interactor import \
    RemoveUsersFromGroupInteractor
from ib_notifications.interactors.storages.storage_interface import \
    StorageInterface


class TestRemoveUsersFromGroupInteractor:
    def test_is_invalid_group_id_raise_exception(self):
        group_id = 123
        user_ids = ["1", "2", "3", "4"]
        exception_message = INVALID_GROUP_ID[0]
        exception_res_status = INVALID_GROUP_ID[1]

        presenter_mock = create_autospec(PresenterInterface)
        storage_mock = create_autospec(StorageInterface)
        interactor = RemoveUsersFromGroupInteractor(
            storage=storage_mock
        )

        storage_mock.is_invalid_group_id.return_value = True
        presenter_mock.raise_invalid_group_id_exception.side_effect = NotFound(
            *INVALID_GROUP_ID)

        with pytest.raises(NotFound) as exe:
            interactor.remove_users_from_group_response(
                presenter=presenter_mock,
                group_id=group_id,
                user_ids=user_ids
            )

        assert exception_message == exe.value.message
        assert exception_res_status == exe.value.res_status
        storage_mock.is_invalid_group_id.assert_called_once_with(
            group_id=group_id)
        presenter_mock.raise_invalid_group_id_exception.assert_called_once()

    def test_is_empty_user_ids_raise_exception(self):
        group_id = 1
        user_ids = []
        exception_message = EMPTY_USER_LIST[0]
        exception_res_status = EMPTY_USER_LIST[1]

        presenter_mock = create_autospec(PresenterInterface)
        storage_mock = create_autospec(StorageInterface)
        interactor = RemoveUsersFromGroupInteractor(
            storage=storage_mock
        )

        storage_mock.is_invalid_group_id.return_value = False
        presenter_mock.raise_empty_user_ids_exception.side_effect = \
            ExpectationFailed(*EMPTY_USER_LIST)

        with pytest.raises(ExpectationFailed) as exe:
            interactor.remove_users_from_group_response(
                presenter=presenter_mock,
                group_id=group_id,
                user_ids=user_ids
            )

        assert exception_message == exe.value.message
        assert exception_res_status == exe.value.res_status
        storage_mock.is_invalid_group_id.assert_called_once_with(
            group_id=group_id)
        presenter_mock.raise_empty_user_ids_exception.assert_called_once()

    def test_with_valid_inputs_remove_users_from_group(self):
        group_id = 2
        user_ids = ["1", "2", "3", "4"]

        presenter_mock = create_autospec(PresenterInterface)
        storage_mock = create_autospec(StorageInterface)
        interactor = RemoveUsersFromGroupInteractor(
            storage=storage_mock
        )

        storage_mock.is_invalid_group_id.return_value = False

        interactor.remove_users_from_group_response(
            presenter=presenter_mock,
            group_id=group_id,
            user_ids=user_ids
        )

        storage_mock.is_invalid_group_id.assert_called_once_with(
            group_id=group_id)
        storage_mock.remove_users_from_group.assert_called_once_with(
            group_id=group_id,
            user_ids=user_ids
        )
